// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFd1HKMoc0vJTInxu5P6lS3YD_jrhiIMs',
    appId: '1:426351252007:ios:0494e74e5b68067325f402',
    messagingSenderId: '426351252007',
    projectId: 'cultivai-23def',
    storageBucket: 'cultivai-23def.firebasestorage.app',
    iosBundleId: 'com.example.irrigation',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFd1HKMoc0vJTInxu5P6lS3YD_jrhiIMs',
    appId: '1:426351252007:ios:0494e74e5b68067325f402',
    messagingSenderId: '426351252007',
    projectId: 'cultivai-23def',
    storageBucket: 'cultivai-23def.firebasestorage.app',
    iosBundleId: 'com.example.irrigation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVJXb7jwaGrbgdIhUWwW8fskioCLbgxdA',
    appId: '1:426351252007:web:2b261b3999ac3ec025f402',
    messagingSenderId: '426351252007',
    projectId: 'cultivai-23def',
    authDomain: 'cultivai-23def.firebaseapp.com',
    storageBucket: 'cultivai-23def.firebasestorage.app',
    measurementId: 'G-XQ4HX58X5Y',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVJXb7jwaGrbgdIhUWwW8fskioCLbgxdA',
    appId: '1:426351252007:web:2b261b3999ac3ec025f402',
    messagingSenderId: '426351252007',
    projectId: 'cultivai-23def',
    authDomain: 'cultivai-23def.firebaseapp.com',
    storageBucket: 'cultivai-23def.firebasestorage.app',
    measurementId: 'G-XQ4HX58X5Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnettVoEEezmi37nJyLhWQln3vvgCypW0',
    appId: '1:426351252007:android:2216e884a584965e25f402',
    messagingSenderId: '426351252007',
    projectId: 'cultivai-23def',
    storageBucket: 'cultivai-23def.firebasestorage.app',
  );
}
